version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: ws_user
          POSTGRES_DB: ws_test
          POSTGRES_PASSWORD: ""

    working_directory: /go/src/github.com/helloeave/worksheets

    steps:
      - checkout

      # postgres
      - run: sudo apt install postgresql-client
      - run: psql ws_test ws_user -h localhost -p 5432 -f /go/src/github.com/helloeave/worksheets/db/schema.sql

      # golang
      - run: go get -v -t -d ./...
      - run: go test -v ./...
